development:
  clients:
    default:
      database: notes_server_development
      hosts:
        - <%= ENV['MONGODB_HOST'] || 'localhost:27017' %>

test:
  clients:
    default:
      database: notes_server_test
      hosts:
        - <%= ENV['MONGODB_HOST'] || 'localhost:27017' %>

production:
  clients:
    default:
      database: notes_server_production
      hosts:
        - <%= ENV['MONGODB_HOST'] || 'localhost:27017' %>
